<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>ZoKrates</string>
    <key>fileTypes</key>
    <array>
      <string>zok</string>
    </array>
    <key>scope</key>
	<string>zok</string>
	<key>scopeName</key>
	<string>source.zok</string>
	<key>uuid</key>
	<string>8E585A63-441D-4A91-8848-BD7C744667CC</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>attributes</string>
        <key>name</key>
        <string>meta.attribute.zokrates</string>
        <key>begin</key>
        <string>(#)(\!?)(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.attribute.zokrates</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.attribute.inner.zokrates</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.attribute.zokrates</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.attribute.zokrates</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#block-comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>line comments</string>
            <key>name</key>
            <string>comment.line.double-slash.zokrates</string>
            <key>match</key>
            <string>\s*//.*</string>
          </dict>
        </array>
      </dict>
      <key>block-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>empty block comments</string>
            <key>name</key>
            <string>comment.block.zokrates</string>
            <key>match</key>
            <string>/\*\*/</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>block comments</string>
            <key>name</key>
            <string>comment.block.zokrates</string>
            <key>begin</key>
            <string>/\*(?!\*)</string>
            <key>end</key>
            <string>\*/</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>ALL CAPS constants</string>
            <key>name</key>
            <string>constant.other.caps.zokrates</string>
            <key>match</key>
            <string>\b[A-Z]{2}[A-Z0-9_]*\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>decimal integers and floats</string>
            <key>name</key>
            <string>constant.numeric.decimal.zokrates</string>
            <key>match</key>
            <string>\b\d[\d_]*(?:u128|u16|u32|u64|u8|f)?\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>hexadecimal integers</string>
            <key>name</key>
            <string>constant.numeric.hex.zokrates</string>
            <key>match</key>
            <string>\b0x[\da-fA-F_]+\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>booleans</string>
            <key>name</key>
            <string>constant.language.bool.zokrates</string>
            <key>match</key>
            <string>\b(true|false)\b</string>
          </dict>
        </array>
      </dict>
      <key>imports</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>explicit import statement</string>
            <key>name</key>
            <string>meta.import.explicit.zokrates</string>
            <key>match</key>
            <string>\b(from)\s+(\".*\")(import)\s+([A-Za-z0-9_]+)\s+((as)\s+[A-Za-z0-9_]+)?\b</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>main import statement</string>
            <key>name</key>
            <string>meta.import.explicit.zokrates</string>
            <key>match</key>
            <string>\b(import)\s+(\".*\")\s+((as)\s+[A-Za-z0-9_]+)?\b</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constant-definitions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>constant definition</string>
            <key>name</key>
            <string>constant.definition.zokrates</string>
            <key>match</key>
            <string>\b(const)\s+([A-Za-z0-9_]+)\s+([A-Za-z0-9_]+)\s+=\s+(?:.+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.const.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.zokrates</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.constant.zokrates</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>function definition</string>
            <key>name</key>
            <string>meta.function.definition.zokrates</string>
            <key>begin</key>
            <string>\b(def)\s+([A-Za-z0-9_]+)((\()|(&lt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.def.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.zokrates</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\:|;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.punctuation.colon.zokrates</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>function/method calls, chaining</string>
            <key>name</key>
            <string>meta.function.call.zokrates</string>
            <key>begin</key>
            <string>([A-Za-z0-9_]+)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>function/method calls with turbofish</string>
            <key>name</key>
            <string>meta.function.call.zokrates</string>
            <key>begin</key>
            <string>([A-Za-z0-9_]+)(?=::&lt;.*&gt;\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>argument visibility</string>
            <key>name</key>
            <string>keyword.visibility.zokrates</string>
            <key>match</key>
            <string>\b(public|private)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>control flow keywords</string>
            <key>name</key>
            <string>keyword.control.zokrates</string>
            <key>match</key>
            <string>\b(do|else|for|do|endfor|if|then|fi|return|assert)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>storage keywords</string>
            <key>name</key>
            <string>storage.type.zokrates</string>
            <key>match</key>
            <string>\b(struct)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>const</string>
            <key>name</key>
            <string>keyword.other.const.zokrates</string>
            <key>match</key>
            <string>\bconst\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>def</string>
            <key>name</key>
            <string>keyword.other.def.zokrates</string>
            <key>match</key>
            <string>\bdef\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>import keywords</string>
            <key>name</key>
            <string>keyword.other.import.zokrates</string>
            <key>match</key>
            <string>\b(import|from|as)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>logical operators</string>
            <key>name</key>
            <string>keyword.operator.logical.zokrates</string>
            <key>match</key>
            <string>(\^|\||\|\||&amp;|&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>single equal</string>
            <key>name</key>
            <string>keyword.operator.assignment.equal.zokrates</string>
            <key>match</key>
            <string>(?&lt;![&lt;&gt;])=(?!=|&gt;)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>comparison operators</string>
            <key>name</key>
            <string>keyword.operator.comparison.zokrates</string>
            <key>match</key>
            <string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>math operators</string>
            <key>name</key>
            <string>keyword.operator.math.zokrates</string>
            <key>match</key>
            <string>(([+%]|(\*(?!\w)))(?!=))|(-(?!&gt;))|(/(?!/))</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>less than, greater than (special case)</string>
            <key>match</key>
            <string>(?:\b|(?:(\))|(\])|(\})))[ \t]+([&lt;&gt;])[ \t]+(?:\b|(?:(\()|(\[)|(\{)))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.square.zokrates</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.zokrates</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.comparison.zokrates</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.zokrates</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.square.zokrates</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.zokrates</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>dot access</string>
            <key>name</key>
            <string>keyword.operator.access.dot.zokrates</string>
            <key>match</key>
            <string>\.(?!\.)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>ranges, range patterns</string>
            <key>name</key>
            <string>keyword.operator.range.zokrates</string>
            <key>match</key>
            <string>\.{2}(=|\.)?</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>colon</string>
            <key>name</key>
            <string>keyword.operator.colon.zokrates</string>
            <key>match</key>
            <string>:(?!:)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>dashrocket, skinny arrow</string>
            <key>name</key>
            <string>keyword.operator.arrow.skinny.zokrates</string>
            <key>match</key>
            <string>-&gt;</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>numeric types</string>
            <key>match</key>
            <string>(?&lt;![A-Za-z])(u128|u16|u32|u64|u8|field)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.zokrates</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>parameterized types</string>
            <key>begin</key>
            <string>\b([A-Z][A-Za-z0-9]*)(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.zokrates</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>primitive types</string>
            <key>name</key>
            <string>entity.name.type.primitive.zokrates</string>
            <key>match</key>
            <string>\b(bool)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>struct declarations</string>
            <key>match</key>
            <string>\b(struct)\s+([A-Z][A-Za-z0-9]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.struct.zokrates</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>types</string>
            <key>name</key>
            <string>entity.name.type.zokrates</string>
            <key>match</key>
            <string>\b[A-Z][A-Za-z0-9]*\b(?!!)</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>comma</string>
            <key>name</key>
            <string>punctuation.comma.zokrates</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>parentheses, round brackets</string>
            <key>name</key>
            <string>punctuation.brackets.round.zokrates</string>
            <key>match</key>
            <string>[()]</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>square brackets</string>
            <key>name</key>
            <string>punctuation.brackets.square.zokrates</string>
            <key>match</key>
            <string>[\[\]]</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>angle brackets</string>
            <key>name</key>
            <string>punctuation.brackets.angle.zokrates</string>
            <key>match</key>
            <string>(?&lt;!=)[&lt;&gt;]</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>double-quoted strings and byte strings</string>
            <key>name</key>
            <string>string.quoted.double.zokrates</string>
            <key>begin</key>
            <string>(b?)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.byte.raw.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.zokrates</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>double-quoted raw strings and raw byte strings</string>
            <key>name</key>
            <string>string.quoted.double.zokrates</string>
            <key>begin</key>
            <string>(b?r)(#*)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.byte.raw.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.raw.zokrates</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.zokrates</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")(\2)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.zokrates</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.raw.zokrates</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>variables</string>
            <key>name</key>
            <string>variable.other.zokrates</string>
            <key>match</key>
            <string>\b(?&lt;!(?&lt;!\.)\.)[a-z0-9_]+\b</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>